export default class Constants {
  static readonly FULL_SCREEN: string = '100%';
  static readonly AUTO: string = 'auto';

  static readonly SPACE_16: number = 16;
  static readonly SPACE_12: number = 12;
  static readonly SPACE_8: number = 8;
  static readonly SPACE_4: number = 4;

  static readonly COLOR_MAIN_THEME = '#4285F4'

  static readonly COLORS = [
    '#9D2933',
    '#4E84C3',
    '#F8CBA6',
    '#5D5132',
    '#D9B6A3',
    '#7A4D2E',
    '#A98175',
    '#E5C8A6',
    '#C77C43',
    '#8A2E22',
    '#6B473C',
    '#F0C2A2',
    '#D6B372',
    '#B36D61',
    '#E5D1B8',
    '#4A4035',
    '#9E8447',
    '#7A3B2E',
    '#D4B59E',
    '#A67A53'
  ]
}
